%% Automate Importing Data by Generating Code Using the Database Explorer App
% This code reproduces the data obtained using the Database Explorer app by
% connecting to a database, executing a SQL query, and importing data into the
% MATLAB(R) workspace. To use this code, add the password for connecting to the
% database in the database command.

% Auto-generated by MATLAB Version 9.5 (R2018b) and Database Toolbox Version 9.0 on 20-Nov-2018 20:29:59

%% Make connection to database
conn = database('SIDDI030','','');

%% Execute query and fetch results
data = fetch(conn,['SELECT * ' ...
    'FROM PCA.dbo.PCA']);
%% Close connection to database
close(conn)

%% Clear variables
clear conn


%Converting SQL table to matrix in MATLAB (the matrix will lose the tickers
%as column headers)
A = table2array(data);

%Specifies what columns of the matrix are tech stocks, and which are of
%diverse sectors
TechStocks = A(:,4:7);
DiverseStocks = A(:,1:4);

%Returns diagonal matrix (eigVal*) of eigenvalues and matrix (eigVect*) 
%whose columns are the corresponding right eigenvectors.
[eigVectTech, eigValTech] = eig(cov(diff(log(TechStocks))));
[eigVectDiverse, eigValDiverse] = eig(cov(diff(log(DiverseStocks))));

%Calculating the weight of each eigenvalue (which corresponds to a particular
%stock) which can be interpreted as that stock's percent contribution to
%the variance in a tech sector portfolio comprised of the 4 tech stocks.
DiagTech = diag(eigValTech);
eigTechOne = DiagTech(1)/sum(DiagTech);
eigTechTwo = DiagTech(2)/sum(DiagTech);
eigTechThree = DiagTech(3)/sum(DiagTech);
eigTechFour = DiagTech(4)/sum(DiagTech);

%Calculating the weight of each eigenvalue (which corresponds to a particular
%stock) which can be interpreted as that stock's percent contribution to
%the variance in a diverse sector portfolio comprised of the 4 diverse sector stocks.
DiagDiverse = diag(eigValDiverse);
eigDiverseOne = DiagDiverse(1)/sum(DiagDiverse);
eigDiverseTwo = DiagDiverse(2)/sum(DiagDiverse);
eigDiverseThree = DiagDiverse(3)/sum(DiagDiverse);
eigDiverseFour = DiagDiverse(4)/sum(DiagDiverse);

%Selecting largest proportion of variance
T = [eigTechOne, eigTechTwo, eigTechThree, eigTechFour];
D = [eigDiverseOne, eigDiverseTwo, eigDiverseThree, eigDiverseFour];
LargestTechVar = max(T);
LargestDiverseVar = max(D);

fprintf("Tech Stocks: AMZN, MSFT, GOOG, AAPL\n")
fprintf("Diversified Stocks: XOM, KO, MMM, AMZN\n")
fprintf("Tech Sector eigenvalues:\n")
fprintf("%d\n", DiagTech)
fprintf("Mixed Sector eigenvalues:\n")
fprintf("%d\n", DiagDiverse)
fprintf("Proportion of variation explained by largest Tech sector eigenvalue: %d\n", LargestTechVar)
fprintf("Proportion of variation explained by largest Mixed sector eigenvalue: %d\n", LargestDiverseVar)

%In the Diversified portfolio, 2 of the stocks explain about 75% of the
%variance. With another stock contributing 10%, and the last contributing
%6%.

%This is moderate contrast to the Tech portfolio, where 2 of the stocks
%explained about 87% of the variance. The other two stocks only explain 12%
%combined. We can infer that since the previous portfolio was diversified,
%each of the stocks shared a (relatively) more equal portion of the
%variance than the non-diversifed tech portfolio (due to stock correlation). In the Tech sector portfolio, large swings in any
%of the tech stocks would not be offset by a stock in another negatively
%correlated sector.

%In addition, typically in PCA analysis, it only takes a few principal
%components to explain a majority of the variance in the dataset. So the
%fact that we see two stocks in each of the portfolios contributing to most
%of the variance in their respective portfolios is to be expected.

